<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jeff Loomis, Sanil Katula, Shahil Patel, Max Chang">
<meta name="dcterms.date" content="2025-11-05">

<title>Biomarkers of ASD</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-fc78cc84e086300a0584af8142339858.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="report_files/libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="report_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="report_files/libs/viz-1.8.2/viz.js"></script>
<link href="report_files/libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
<script src="report_files/libs/grViz-binding-1.0.11/grViz.js"></script>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biomarkers of ASD</h1>
<p class="subtitle lead">Evaluating the impact of preprocessing, outlier detection, and selection strategies on ASD biomarker accuracy</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jeff Loomis, Sanil Katula, Shahil Patel, Max Chang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Updated</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 5, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>In this proteomics analysis of 154 boys and 1,317 serum proteins, we examined biomarkers for distinguishing autism spectrum disorder (ASD) from typically developing (TD) controls and tested how different modeling choices affected results. After log10 transformation, z-scoring, and ±3 SD trimming, the baseline model used t-tests and Random Forests to select the top 10 proteins from each method, intersecting on five (DERM, RELT, MRC2, IgD, Cadherin-5). Logistic regression on these achieved 77.4% accuracy and 88.3% AUC. Three variations showed that (1) doing feature selection only on training data reduced performance (68.8% accuracy, 71.5% AUC), (2) expanding to the top 25 proteins improved it (83.9% accuracy, 95.0% AUC), and (3) using a fuzzy intersection (union) lowered it (67.7% accuracy, 78.3% AUC). A simpler LASSO model with cross-validation selected three proteins (DERM, IgD, eIF-4H), giving 67.7% accuracy and 75.8% AUC with higher specificity (86.7%) but lower sensitivity (50.0%). Overall, the five-protein baseline best balances sensitivity and specificity, while the LASSO model shows that a smaller panel can still perform reasonably well, highlighting a trade-off between simplicity and performance.</p>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<p>A total of 154 pediatric subjects were enrolled in the study, consisting of 76 boys with autism spectrum disorder (ASD; mean age 5.6 years, SD 1.7) and 78 typically developing (TD) boys (mean age 5.7 years, SD 2.0). The ethnic distribution was 73 White/Caucasian, 32 Hispanic/Latino, 17 African American/Black, 5 Asian or Pacific Islander, 23 of multiple or other ethnicities, and 4 not reported. Autism Diagnostic Observation Schedule (ADOS) scores were also collected for all participants.</p>
<p>Serum protein expression was measured using the SOMAscan® assay, which quantified 1,317 proteins in 150 μl serum from 154 participants. An additional 14 blinded duplicate samples (7 ASD, 7 TD) were run for quality control but not included in analyses. In the published study, 192 proteins were removed during quality control, leaving 1,125 for analysis. The dataset used here retains all 1,317 raw protein measurements prior to filtering. These proteins span a broad range of functional classes, including cytokines, growth factors, receptors, and signaling molecules. Protein levels were reported as relative fluorescence units (RFUs), reflecting their relative abundance.</p>
<p>Preprocessing for the present analysis involved three main steps applied to all protein measures: a log10 transform to stabilize variance and reduce skew, z-score standardization (mean 0, SD 1) to place proteins on a comparable scale, and trimming at ±3 SD to cap extreme outliers. After these transformations, the dataset was organized with group and ados leading, followed by the processed protein features, and saved in R binary format (<code>biomarker_clean</code>) for downstream statistical analysis.</p>
</section>
<section id="summary-of-published-analysis" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-published-analysis">Summary of published analysis</h2>
<p>The study by Hewitson et al.&nbsp;(2021) aimed to identify serum protein biomarkers that could distinguish children with autism spectrum disorder (ASD) from typically developing (TD) controls. Blood samples from 154 male children (76 ASD and 78 TD) were analyzed using the SOMAscan® 1.3K proteomic platform, which quantified 1,317 serum proteins. After quality control procedures excluded 192 proteins, the remaining 1,125 were log transformed, standardized to z-scores, and values beyond ±3 standard deviations were trimmed to reduce the influence of extreme outliers.</p>
<p>Three feature selection approaches were applied: two-sample t-tests comparing ASD and TD groups, random forest importance rankings, and Spearman correlations between protein levels and ADOS scores. From each method, the ten most informative proteins were selected, and the overlapping set across all three approaches consisted of IgD, suPAR, MAPK14, EPHB2, and DERM, which defined the core panel.</p>
<p>Logistic regression models were then used to evaluate classification performance and to assess whether adding additional proteins could improve accuracy. Four additional proteins, ROR1, GI24, eIF-4H, and ARSB, each improved classification performance when added to the five-protein core set. The combined nine-protein optimal panel achieved an AUC of 86% (sensitivity 83%, specificity 84%).</p>
<section id="workflow-of-hewitson-et-al.-2021-biomarker-analysis" class="level4">
<h4 class="anchored" data-anchor-id="workflow-of-hewitson-et-al.-2021-biomarker-analysis">Workflow of Hewitson et al.&nbsp;(2021) Biomarker Analysis</h4>
<div class="cell">
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-152ef977520512f8841a" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-152ef977520512f8841a">{"x":{"diagram":"\ndigraph G {\n  rankdir=TB;\n  graph [splines=true, nodesep=0.6, ranksep=0.5];\n  node  [shape=box, style=\"rounded,filled\", fillcolor=\"#F5F7FA\", color=\"#94A3B8\", fontname=\"Helvetica\"];\n  edge  [color=\"#94A3B8\"];\n\n  # Top row (data & preprocessing)\n  A [label=\"Serum samples\\n154 boys (76 ASD, 78 TD)\"];\n  B [label=\"SOMAscan 1.3K\\n1,317 proteins\"];\n  C [label=\"Protein QC\\nremove 192\"];\n  D [label=\"Retained\\n1,125 proteins\"];\n  E [label=\"Preprocessing\\nlog10 transform, z-score, trim ±3 SD\"];\n\n  # Second row (feature selection & modeling)\n  M1 [label=\"t-tests\\n(ASD vs TD)\"];\n  M2 [label=\"Random forest\\nimportance\"];\n  M3 [label=\"Spearman correlation\\nwith ADOS\"];\n  CORE [label=\"Overlap of top 10\\nfrom each method\\nIgD, suPAR, MAPK14, EPHB2, DERM\"];\n  ADD4 [label=\"Add 4 proteins\\nROR1, GI24, eIF-4H, ARSB\"];\n  LR [label=\"Logistic regression\\nmodeling\"];\n  FINAL [label=\"Final classifier\\n9-protein panel\\nAUC 86% (sens 83%, spec 84%)\"];\n\n  {rank=same; M1; M2; M3}\n\n  A -> B -> C -> D -> E;\n  E -> M1;\n  E -> M2;\n  E -> M3;\n\n  M1 -> CORE;\n  M2 -> CORE;\n  M3 -> CORE;\n\n  CORE -> ADD4 -> LR -> FINAL;\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
</section>
<section id="findings" class="level2">
<h2 class="anchored" data-anchor-id="findings">Findings</h2>
<p>Summarize your findings here. I’ve included some subheaders in a way that seems natural to me; you can structure this section however you like.</p>
<section id="impact-of-preprocessing" class="level3">
<h3 class="anchored" data-anchor-id="impact-of-preprocessing">Impact of preprocessing</h3>
<section id="log-transformation-of-protein-intensities" class="level4">
<h4 class="anchored" data-anchor-id="log-transformation-of-protein-intensities">Log-transformation of protein intensities</h4>
<p>To assess the effect of log-transformation, I compared raw versus log10-transformed protein intensities.<br>
On the raw scale, most proteins were strongly right-skewed (median skew ≈ 2.0).<br>
After applying the log10 transform (with a small positive shift for non-positive values), distributions became substantially more symmetric (median skew ≈ 0.2).<br>
About 70 % of proteins showed reduced absolute skewness, and the relationship between the mean and standard deviation was much weaker, indicating partial variance stabilization.</p>
<p>Overall, the log10 transformation reduces skewness, tames extreme high values, and stabilizes variance—important for statistical models that assume approximate normality and homoscedasticity.</p>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="q1_log/hist_raw_sample.png" class="img-fluid figure-img"></p>
<figcaption>Distributions of raw (left) and log10-transformed (right) protein intensities for a random sample of nine proteins.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="q1_log/hist_log_sample.png" class="img-fluid figure-img"></p>
<figcaption>Distributions of raw (left) and log10-transformed (right) protein intensities for a random sample of nine proteins.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="q1_log/qq_raw_sample.png" class="img-fluid figure-img"></p>
<figcaption>Distributions of raw (left) and log10-transformed (right) protein intensities for a random sample of nine proteins.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="q1_log/qq_log_sample.png" class="img-fluid figure-img"></p>
<figcaption>Distributions of raw (left) and log10-transformed (right) protein intensities for a random sample of nine proteins.</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="q1_log/mean_sd_raw.png" class="img-fluid figure-img"></p>
<figcaption>Distributions of raw (left) and log10-transformed (right) protein intensities for a random sample of nine proteins.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="q1_log/mean_sd_log.png" class="img-fluid figure-img"></p>
<figcaption>Distributions of raw (left) and log10-transformed (right) protein intensities for a random sample of nine proteins.</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="outliers-analysis" class="level3">
<h3 class="anchored" data-anchor-id="outliers-analysis">Outliers Analysis</h3>
<p>Outlier analysis of per-subject counts (|z| &gt; 3) showed that ASD and TD groups had similar medians (both 8.5; Wilcoxon p = 0.82), but TD participants exhibited greater dispersion with higher means, larger maxima, and a heavier right tail. Using Tukey’s 1.5×IQR rule, 9 of 78 TD participants (11.5%) were flagged as outliers compared to 4 of 76 ASD participants (5.3%). Overall, while the central tendency of outlier counts was similar across groups, extreme outlying subjects were more common in the TD group.</p>
<p><strong>Group summaries</strong><br>
</p>
<p>We computed a per-subject outlier count as the number of proteins with (|z|&gt;3) after log10 transformation and z-scoring. The first table summarizes these counts by group (ASD vs TD), reporting (N), mean, median, SD, and range. Both groups had similar medians (8.5), but TD subjects showed greater variability, with a higher mean (17.6 compared to 13.3) and a wider range of values (0–157 versus 0–126). The second table shows how often subjects exceeded selected thresholds (≥10, 25, 50, 100, and 200 outliers). Across all thresholds, a larger proportion of TD participants were above each cutoff, indicating more frequent extreme outlier counts. Together, these summaries show that while the typical number of outliers per subject was comparable between groups, the TD distribution extended further to the right, with a slightly larger number of subjects showing unusually high outlier counts.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Per-subject outlier counts (|z| &gt; 3) after log10 transform and z-scoring (no trimming)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">group</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ASD</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">13.25</td>
<td style="text-align: right;">8.5</td>
<td style="text-align: right;">19.82</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">126</td>
</tr>
<tr class="even">
<td style="text-align: left;">TD</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">17.59</td>
<td style="text-align: right;">8.5</td>
<td style="text-align: right;">29.25</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">157</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Proportion of subjects with outlier counts at or above selected thresholds (|z| &gt; 3)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">group</th>
<th style="text-align: right;">threshold</th>
<th style="text-align: right;">num_at_or_above</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ASD</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">0.434</td>
</tr>
<tr class="even">
<td style="text-align: left;">TD</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">0.397</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ASD</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">0.066</td>
</tr>
<tr class="even">
<td style="text-align: left;">TD</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">0.141</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ASD</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">0.026</td>
</tr>
<tr class="even">
<td style="text-align: left;">TD</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">0.064</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ASD</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">0.026</td>
</tr>
<tr class="even">
<td style="text-align: left;">TD</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">0.051</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ASD</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">TD</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>&nbsp;</p>
<p><strong>Descriptive distributions (histogram &amp; boxplot)</strong><br>
</p>
<p>The histogram of per-subject outlier counts shows that both ASD and TD groups cluster around similar values, but the TD group has a heavier right tail, with more subjects showing very high counts. The boxplot confirms this: medians are identical across groups, but TD participants show greater spread and more extreme high values. Tukey-flagged outlier participants are visible as red points in the boxplot.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;</p>
<p><strong>Group Comparisons of Outlier Counts</strong><br>
</p>
<p>The Wilcoxon rank-sum test showed no significant difference in median outlier counts between ASD and TD participants ((W = 3028.5), (p = 0.82)). Using Tukey’s 1.5×IQR rule, 9 of 78 TD participants (11.5%) and 4 of 76 ASD participants (5.3%) were flagged as outliers. The chi-square test comparing these proportions was not significant, indicating that while extreme subjects occurred in both groups, they were slightly more common among TD participants without reaching statistical significance.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Wilcoxon rank-sum test comparing per-subject outlier counts (ASD vs TD)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">test</th>
<th style="text-align: right;">W</th>
<th style="text-align: right;">p_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Wilcoxon rank-sum</td>
<td style="text-align: right;">3028.5</td>
<td style="text-align: right;">0.8166471</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Flagged outlier participants by group (Tukey 1.5×IQR rule) with proportions</caption>
<thead>
<tr class="header">
<th style="text-align: left;">group</th>
<th style="text-align: left;">is_outlier</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">prop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ASD</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">0.9473684</td>
</tr>
<tr class="even">
<td style="text-align: left;">ASD</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.0526316</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TD</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">0.8846154</td>
</tr>
<tr class="even">
<td style="text-align: left;">TD</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.1153846</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>2×2 contingency table: flagged (TRUE/FALSE) by group</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">FALSE</th>
<th style="text-align: right;">TRUE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ASD</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">TD</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">9</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Chi-square test comparing flagged proportions across groups</caption>
<thead>
<tr class="header">
<th style="text-align: left;">test</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">p_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chi-square test of independence</td>
<td style="text-align: right;">1.233372</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.2667523</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>&nbsp;</p>
<p><strong>Overall interpretation</strong><br>
</p>
<ul>
<li>Both groups share a similar central tendency (same medians, Wilcoxon not significant).<br>
</li>
<li>The TD group shows greater dispersion and heavier tails, including more extreme subjects.<br>
</li>
<li>Using Tukey’s rule, a larger proportion of TD participants were classified as outliers compared with ASD.</li>
</ul>
<p><strong>Outlier Analysis Conclusion:</strong> While typical participants look similar in ASD and TD, extremely outlying individuals are more common in the TD group.</p>
</section>
</section>
<section id="methodological-variations" class="level2">
<h2 class="anchored" data-anchor-id="methodological-variations">Methodological variations</h2>
<p>We were then tasked to find out what happens to the model under these 3 modifications:</p>
<p>1) Repeat the analysis but carry out the entire selection procedure on a training partition – in other words, set aside some testing data at the very beginning and don’t use it until you are evaluating accuracy at the very end.</p>
<p>2) Choose a larger number (more than ten) of top predictive proteins using each selection method.</p>
<p>3) Use a fuzzy intersection instead of a hard intersection to combine the sets of top predictive proteins across selection methods.</p>
<section id="original-model" class="level3">
<h3 class="anchored" data-anchor-id="original-model">Original Model:</h3>
<p>The original model produces the following result:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    ASD TD class.error
ASD  49 27   0.3552632
TD   21 57   0.2692308</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 sensitivity binary         0.812
2 specificity binary         0.733
3 accuracy    binary         0.774
4 roc_auc     binary         0.883</code></pre>
</div>
</div>
<ul>
<li><p>RF OOB Error: Based on all 154 subjects.</p></li>
<li><p>Final Accuracy: 77.4%</p></li>
<li><p>Final AUC: 88.3%</p>
<p>One problem from this method is that the feature selection was performed on the entire data set before splitting. This means the selection process “peeked” at the test data, choosing features that were already known to work well on it. This inflates the final score. The other methods would have a lower score than this.</p></li>
</ul>
</section>
<section id="variation-1" class="level3">
<h3 class="anchored" data-anchor-id="variation-1">Variation 1:</h3>
<p>Repeat the analysis but carry out the entire selection procedure on a training partition – in other words, set aside some testing data at the very beginning and don’t use it until you are evaluating accuracy at the very end.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    ASD TD class.error
ASD  39 21   0.3500000
TD   16 46   0.2580645</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 sensitivity binary         0.562
2 specificity binary         0.812
3 accuracy    binary         0.688
4 roc_auc     binary         0.715</code></pre>
</div>
</div>
<ul>
<li><p>RF OOB Error: Based on the smaller training set (122 subjects)</p></li>
<li><p>Final Accuracy: 68.8%</p></li>
<li><p>Final AUC: 71.5%</p>
<p>The accuracy and AUC dropped a lot. This 68.8% accuracy is the honest and realistic score. The ~9-point drop in accuracy reveals the cost of data leakage. The original model was much more optimistic, and this model leads to more truthful results.</p></li>
</ul>
</section>
<section id="variation-2" class="level3">
<h3 class="anchored" data-anchor-id="variation-2">Variation 2:</h3>
<p>Choose a larger number (more than ten) of top predictive proteins using each selection method. Decided to use n=25 instead of n=10.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    ASD TD class.error
ASD  49 27   0.3552632
TD   21 57   0.2692308</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 sensitivity binary         0.75 
2 specificity binary         0.933
3 accuracy    binary         0.839
4 roc_auc     binary         0.95 </code></pre>
</div>
</div>
<ul>
<li><p>RF OOB Error: Based on all 154 subjects</p></li>
<li><p>Final Accuracy: 83.9%</p></li>
<li><p>Final AUC: 95.0%</p></li>
<li><p>How it was affected: The accuracy and AUC increased dramatically</p>
<p>This suggests that the original model (n=10) was underfit. The features ranked 11-25 still contained valuable information. The model became more complex and could capture more of the underlying signal by including them which leads to better performance.</p></li>
</ul>
</section>
<section id="variation-3" class="level3">
<h3 class="anchored" data-anchor-id="variation-3">Variation 3:</h3>
<p>Use a fuzzy intersection instead of a hard intersection to combine the sets of top predictive proteins across selection methods.</p>
<p>The chnage was using union() for a “fuzzy intersection” instead of intersection.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    ASD TD class.error
ASD  49 27   0.3552632
TD   21 57   0.2692308</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 sensitivity binary         0.562
2 specificity binary         0.8  
3 accuracy    binary         0.677
4 roc_auc     binary         0.783</code></pre>
</div>
</div>
<ul>
<li><p>RF OOB Error: Based on all 154 subjects</p></li>
<li><p>Final Accuracy: 67.7%</p></li>
<li><p>Final AUC: 78.3%</p></li>
<li><p>How it was affected: The accuracy and AUC dropped significantly</p>
<p>This shows the danger of overfitting. The original intersection is a strict filter and keeps only high confidence features that both methods agreed on, while the union is a permissive filter and keeps features that either method liked. The union added more noise than signal and caused the model to drop in performance.</p></li>
</ul>
</section>
<section id="improved-classifier" class="level3">
<h3 class="anchored" data-anchor-id="improved-classifier">Improved classifier</h3>
<section id="motivation-seeking-a-simpler-biomarker-panel" class="level4">
<h4 class="anchored" data-anchor-id="motivation-seeking-a-simpler-biomarker-panel">Motivation: Seeking a simpler biomarker panel</h4>
<p>While the in-class analysis identified a 5-protein panel with strong classification accuracy (77.4% accuracy, 88.3% AUC), clinical translation of biomarker panels benefits from simplicity. Fewer proteins mean lower assay costs, faster turnaround times, and reduced technical variability. We therefore sought to identify a minimal protein panel that maintains comparable diagnostic performance.</p>
</section>
<section id="approach-lasso-regularization-for-automatic-feature-selection" class="level4">
<h4 class="anchored" data-anchor-id="approach-lasso-regularization-for-automatic-feature-selection">Approach: LASSO regularization for automatic feature selection</h4>
<p>We employed LASSO (Least Absolute Shrinkage and Selection Operator) regression, a penalized logistic regression method that performs automatic feature selection via L1 regularization. LASSO works by adding a penalty term proportional to the absolute value of coefficients, which shrinks less important features exactly to zero, effectively removing them from the model. This makes LASSO particularly well-suited for high-dimensional biomarker data where interpretability and parsimony are valued.</p>
<p>Our methodological workflow consisted of five steps:</p>
<ol type="1">
<li><p><strong>Baseline replication</strong>: We first replicated the in-class analysis to establish benchmark performance metrics using the same random seed and procedures.</p></li>
<li><p><strong>Candidate expansion</strong>: Rather than using only the strict intersection of t-test and Random Forest top-10 lists (which yielded 5 proteins), we used the <em>union</em> of both lists to create a larger candidate pool (15 proteins total). This gave LASSO more features to consider while still focusing on biologically relevant candidates.</p></li>
<li><p><strong>LASSO feature selection</strong>: We applied 10-fold cross-validation on the training set to select the optimal regularization strength (λ). Following best practices, we used the “1 standard error rule” (λ<sub>1SE</sub>) to favor a simpler model with slightly higher regularization, as it tends to generalize better and reduces overfitting.</p></li>
<li><p><strong>Model evaluation</strong>: We evaluated the LASSO-regularized logistic regression on the held-out test set and computed sensitivity, specificity, accuracy, and ROC-AUC.</p></li>
<li><p><strong>Comparison</strong>: We also fit a standard (unpenalized) logistic regression using only the LASSO-selected features to assess whether the regularization itself improved performance beyond simple feature selection.</p></li>
</ol>
</section>
<section id="workflow-diagram" class="level4">
<h4 class="anchored" data-anchor-id="workflow-diagram">Workflow diagram</h4>
<div class="cell">
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-1085653a7aa1c7ce6ad5" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-1085653a7aa1c7ce6ad5">{"x":{"diagram":"\ndigraph G {\n  rankdir=TB;\n  graph [splines=true, nodesep=0.6, ranksep=0.5];\n  node  [shape=box, style=\"rounded,filled\", fillcolor=\"#F5F7FA\", color=\"#94A3B8\", fontname=\"Helvetica\"];\n  edge  [color=\"#94A3B8\"];\n\n  # Top row\n  A [label=\"Preprocessed data\\n(biomarker_clean)\\n154 subjects, 1,317 proteins\"];\n  \n  # Feature selection\n  M1 [label=\"t-tests\\nTop 10 proteins\"];\n  M2 [label=\"Random Forest\\nTop 10 proteins\"];\n  \n  # Baseline vs New\n  BASELINE [label=\"Baseline approach\\nIntersection\\n5 proteins\", fillcolor=\"#FEF3C7\"];\n  UNION [label=\"LASSO approach\\nUnion (candidate pool)\\n15 proteins\", fillcolor=\"#DBEAFE\"];\n  \n  # LASSO\n  LASSO [label=\"LASSO regression\\n10-fold CV\\nλ selection (1SE rule)\", fillcolor=\"#DBEAFE\"];\n  SELECTED [label=\"LASSO-selected features\\n3 proteins\\nDERM, IgD, eIF-4H\", fillcolor=\"#DBEAFE\"];\n  \n  # Final models\n  BASELINE_GLM [label=\"Baseline GLM\\n5 proteins\\nAcc: 77.4%, AUC: 88.3%\", fillcolor=\"#FEF3C7\"];\n  LASSO_GLM [label=\"LASSO-regularized GLM\\n3 proteins\\nAcc: 67.7%, AUC: 75.8%\", fillcolor=\"#DBEAFE\"];\n  \n  {rank=same; M1; M2}\n  {rank=same; BASELINE; UNION}\n\n  A -> M1;\n  A -> M2;\n  \n  M1 -> BASELINE;\n  M2 -> BASELINE;\n  \n  M1 -> UNION;\n  M2 -> UNION;\n  \n  BASELINE -> BASELINE_GLM;\n  \n  UNION -> LASSO;\n  LASSO -> SELECTED;\n  SELECTED -> LASSO_GLM;\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="results" class="level4">
<h4 class="anchored" data-anchor-id="results">Results</h4>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Performance comparison: Baseline intersection vs.&nbsp;LASSO-based feature selection</caption>
<colgroup>
<col style="width: 31%">
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">method</th>
<th style="text-align: right;">n_proteins</th>
<th style="text-align: right;">sensitivity</th>
<th style="text-align: right;">specificity</th>
<th style="text-align: right;">accuracy</th>
<th style="text-align: right;">roc_auc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Baseline (Intersection)</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.812</td>
<td style="text-align: right;">0.733</td>
<td style="text-align: right;">0.774</td>
<td style="text-align: right;">0.883</td>
</tr>
<tr class="even">
<td style="text-align: left;">LASSO Panel</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.500</td>
<td style="text-align: right;">0.867</td>
<td style="text-align: right;">0.677</td>
<td style="text-align: right;">0.758</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standard GLM on LASSO</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.562</td>
<td style="text-align: right;">0.800</td>
<td style="text-align: right;">0.677</td>
<td style="text-align: right;">0.713</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The baseline approach using the intersection of t-test and Random Forest selections yielded a 5-protein panel (DERM, RELT, MRC2, IgD, Cadherin-5) with strong performance: 77.4% accuracy, 81.3% sensitivity, 73.3% specificity, and 88.3% AUC.</p>
<p>LASSO regularization identified a 3-protein panel (DERM, IgD, eIF-4H), achieving 40% complexity reduction (from 5 to 3 proteins). This simpler panel maintained reasonable diagnostic utility with 67.7% accuracy and 75.8% AUC. Notably, two proteins (DERM and IgD) were selected by both approaches, suggesting their robust discriminatory power across methods.</p>
<p>The LASSO panel showed higher specificity (86.7%) but lower sensitivity (50.0%) compared to baseline. This indicates that the simpler model is more conservative, correctly identifying more typically developing (TD) children but missing more ASD cases.</p>
<p>Interestingly, the standard GLM refitted on the LASSO-selected features performed similarly to the regularized LASSO model itself (67.7% accuracy for both, though standard GLM had slightly lower AUC at 71.3%). This suggests that the primary benefit of LASSO in this case was feature selection rather than coefficient shrinkage.</p>
</section>
<section id="selected-proteins-and-coefficients" class="level4">
<h4 class="anchored" data-anchor-id="selected-proteins-and-coefficients">Selected proteins and coefficients</h4>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>LASSO-selected proteins and their regularized coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Protein</th>
<th style="text-align: right;">Coefficient</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DERM</td>
<td style="text-align: right;">-0.3501</td>
</tr>
<tr class="even">
<td style="text-align: left;">eIF-4H</td>
<td style="text-align: right;">-0.1633</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IgD</td>
<td style="text-align: right;">-0.1353</td>
</tr>
<tr class="even">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.0707</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The three selected proteins each contributed meaningfully to classification. DERM (dermatopontin) and IgD (immunoglobulin D) were consistently identified across multiple selection methods, reinforcing their biological relevance. The inclusion of eIF-4H (eukaryotic translation initiation factor 4H) by LASSO but not in the baseline intersection suggests it may capture complementary information when combined with DERM and IgD.</p>
</section>
<section id="interpretation-and-clinical-implications" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-and-clinical-implications">Interpretation and clinical implications</h4>
<p>This analysis demonstrates a fundamental trade-off in biomarker development: <strong>model complexity versus predictive performance</strong>. The LASSO-based 3-protein panel sacrifices approximately 10 percentage points in accuracy and 12 points in AUC compared to the 5-protein baseline, but achieves a 40% reduction in panel size.</p>
<p>From a clinical perspective, this trade-off may be acceptable in certain contexts:</p>
<ul>
<li><p><strong>Screening applications</strong>: Where high specificity is valued to minimize false positives and unnecessary follow-up, the LASSO panel’s 86.7% specificity is attractive.</p></li>
<li><p><strong>Resource-constrained settings</strong>: Fewer proteins reduce assay costs and complexity, potentially improving accessibility.</p></li>
<li><p><strong>Early-stage validation</strong>: A smaller panel may be easier to validate across independent cohorts and platforms.</p></li>
</ul>
<p>However, the lower sensitivity (50%) is concerning for diagnostic applications, as it would miss half of true ASD cases. The baseline 5-protein panel’s more balanced sensitivity (81.3%) and specificity (73.3%) profile may be more appropriate for clinical diagnosis.</p>
<p><strong>Key finding</strong>: LASSO successfully identified a minimal 3-protein signature that maintains moderate diagnostic utility, demonstrating that automated regularization methods can extract parsimonious biomarker panels. However, the performance gap suggests that the 5-protein baseline panel may represent a better balance of complexity and accuracy for this dataset. Future work could explore intermediate panel sizes or alternative regularization approaches (e.g., elastic net) to optimize this trade-off.</p>
</section>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>We evaluated serum proteomic biomarkers for distinguishing boys with autism spectrum disorder (ASD) from typically developing (TD) boys, and we quantified how results change under key modeling design choices. We further explored whether a simpler biomarker panel can retain competitive performance.</p>
<p>Data (n = 154; 1,317 proteins) were preprocessed via log10 transformation, z-score standardization, and trimming at ±3 SD, yielding the analysis set <code>biomarker_clean</code>. The in-class baseline reproduced a two-stage feature selection (two-sample t-tests and Random Forest importance, top 10 each), followed by a hard intersection and logistic regression evaluation on an 80/20 split. We then implemented three methodological variations: (1) performed all selection exclusively on a training partition and evaluated once on a held-out test set; (2) expanded each selection list to the top 25; and (3) used a fuzzy intersection (union) to combine selections. Finally, to pursue a simpler panel (Task 4), we applied LASSO-regularized logistic regression with 10-fold cross-validation (1-SE rule) using the union of the top-10 lists as candidates, and compared against the baseline.</p>
<p>The replicated baseline (5-protein intersection: DERM, RELT, MRC2, IgD, Cadherin-5) achieved accuracy 77.4% and AUC 88.3%. Variation (1) reduced performance (accuracy 68.8%, AUC 71.5%), reflecting the removal of information leakage when selection is confined to the training set. Variation (2) improved performance (accuracy 83.9%, AUC 95.0%) by allowing more informative features into the intersection (top 25). Variation (3) degraded performance (accuracy 67.7%, AUC 78.3%), indicating that the union introduced more noise than signal. The LASSO approach selected a 3-protein panel (DERM, IgD, eIF-4H) with 40% fewer proteins than baseline and reasonable performance (accuracy 67.7%, AUC 75.8%)—higher specificity but lower sensitivity—illustrating the trade-off between simplicity and accuracy.</p>
<p>The baseline 5-protein intersection delivers the best balance of sensitivity and specificity under the original design, while LASSO demonstrates that substantially simpler panels are feasible with modest loss of accuracy. Smaller panels may suit screening or resource-constrained contexts; for diagnosis, the baseline-sized panel is preferred. Future work should evaluate elastic net regularization and intermediate panel sizes on external cohorts.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>